# Travis CI Configuration file
# @link https://travis-ci.org/

# Using Java for the project
language: java
jdk:
# JDK 8 is set to deploy the artifacts and docs
- oraclejdk8
env:
   - DEPLOY=true
   - DEPLOY_DOCS=true

before_install:
  # Gets scripts
  - git clone -b v0.4.2 --single-branch https://github.com/Bernardo-MG/ci-shell-scripts.git ~/.scripts
  # Sets scripts as executable
  - chmod -R +x ~/.scripts/*
  - chmod +x ./.scripts/create-test-databases.sh
  # Prepares CI environment
  - source ~/.scripts/travis/load-travis-environment.sh
before_script:
  # Creates Maven settings
  - ~/.scripts/java/maven/create-maven-settings.sh $VERSION_TYPE
  # Creates test databases
  - ./.scripts/create-test-databases.sh
script:
  # Unit and integration tests are run
  - mvn clean verify
after_success:
  # Documentation deployment script
  - ~/.scripts/java/maven/deploy-site.sh $DO_DEPLOY_DOCS deployment
  # Code artifacts deployment script
  - ~/.scripts/java/maven/deploy.sh $DO_DEPLOY deployment
