# Travis CI Configuration file
# @link https://travis-ci.org/

# Using Java for the project
language: java
services:
  - mysql
  - postgresql
matrix:
  include:
    # Documentation deployed with JDK8
    - jdk: oraclejdk8
      env: DATABASE=h2 PROVIDER=eclipselink DEPLOY_DOCS=true DEPLOY=true
    - jdk: oraclejdk8
      env: DATABASE=h2 PROVIDER=spring-jdbc
    - jdk: oraclejdk8
      env: DATABASE=hsqldb PROVIDER=eclipselink
    - jdk: oraclejdk8
      env: DATABASE=postgres PROVIDER=eclipselink

before_install:
  # Gets scripts
  - git clone -b v1.0.0 --single-branch https://github.com/Bernardo-MG/ci-shell-scripts.git ~/.scripts
  # Sets scripts as executable
  - chmod -R +x ~/.scripts/*
  - chmod +x ./.scripts/create-test-databases.sh
  # Prepares CI environment
  - source ~/.scripts/travis/load-travis-environment.sh
before_script:
  # Creates Maven settings
  - ~/.scripts/java/maven/create-maven-settings.sh $VERSION_TYPE
  # Creates test databases
  - ./.scripts/create-test-databases.sh
script:
  # Unit and integration tests are run
  - mvn clean verify -P $DATABASE,$PROVIDER
after_success:
  # Documentation deployment script
  - ~/.scripts/java/maven/deploy-site.sh $DO_DEPLOY_DOCS deployment
  # Code artifacts deployment script
  - ~/.scripts/java/maven/deploy.sh $DO_DEPLOY deployment
