language: java
jdk:
# JDK 8 is set to deploy the docs in the configuration matrix
#  - oraclejdk8
# JDK 7 is set to deploy the artifacts in the configuration matrix
#  - oraclejdk7
  - openjdk7
services:
  - mysql
  - postgresql
matrix:
  include:
    # Code artifacts deployed with JDK7
    - jdk: oraclejdk7
      env: DEPLOY=true
    # Documentation deployed with JDK8
    - jdk: oraclejdk8
      env: DEPLOY_DOCS=true

before_install:
  # Creates test databases
  - mysql -e "create database IF NOT EXISTS test_jpa_hibernate;" -uroot
  - mysql -e "create database IF NOT EXISTS test_jpa_hibernate_modify;" -uroot
  - mysql -e "create database IF NOT EXISTS test_spring_jdbc;" -uroot
  - mysql -e "create database IF NOT EXISTS test_spring_jdbc_modify;" -uroot
  - mysql -e "create database IF NOT EXISTS test_jpa_eclipselink;" -uroot
  - mysql -e "create database IF NOT EXISTS test_jpa_eclipselink_modify;" -uroot
  - psql -c 'create database test_jpa_hibernate;' -U postgres
  - psql -c 'create database test_jpa_hibernate_modify;' -U postgres
  - psql -c 'create database test_spring_jdbc;' -U postgres
  - psql -c 'create database test_spring_jdbc_modify;' -U postgres
  - psql -c 'create database test_jpa_eclipselink;' -U postgres
  - psql -c 'create database test_jpa_eclipselink_modify;' -U postgres
  # Scripts are set as executable
  - chmod +x ./.scripts/load-travis-environment.sh
  - chmod +x ./.scripts/create-maven-settings.sh
  - chmod +x ./.scripts/deploy.sh
  - chmod +x ./.scripts/deploy-site.sh
  # Prepares CI environment
  - source ./.scripts/load-travis-environment.sh
  # Creates Maven settings
  - ./.scripts/create-maven-settings.sh
script:
  # Unit and integration tests are run
  - mvn clean verify
after_success:
  # Documentation deployment script
  - ./.scripts/deploy-site.sh
  # Code artifacts deployment script
  - ./.scripts/deploy.sh
